name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package --batch-mode

      - name: Run unit tests
        run: mvn test

      - name: Persist WAR file
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts
          cp target/*.war $GITHUB_WORKSPACE/artifacts/
      - name: List artifacts directory
        run: |
          echo "Artifacts in workspace:"
          ls -R $GITHUB_WORKSPACE/artifacts
